import type { CapiEvent, CapiHealth, CrmActivity, Lead, MetaCampaignRoi, Offer, SmartLink, Tenant } from "./types";

export const demoTenants: Tenant[] = [
  {
    id: "tenant-auto",
    slug: "autoescola-vivo",
    name: "Autoescola Vivo",
    whatsapp_number: "5564999999999",
    status: "active",
    default_message_template: "Ola! Tenho interesse em {{oferta}}. Ref: {{ref}}",
  },
  {
    id: "tenant-pet",
    slug: "pet-shop-modelo",
    name: "Pet Shop Modelo",
    whatsapp_number: "5564888888888",
    status: "active",
    default_message_template: "Ola! Quero saber mais sobre {{oferta}}. Ref: {{ref}}",
  },
];

export const demoOffers: Offer[] = [
  {
    id: "offer-cnh-b",
    tenant_id: "tenant-auto",
    name: "CNH Categoria B",
    slug: "cnh-b",
    category: "Autoescola",
    price: 2290,
    status: "active",
  },
  {
    id: "offer-pet-banho",
    tenant_id: "tenant-pet",
    name: "Banho e Tosa",
    slug: "banho-e-tosa",
    category: "Pet shop",
    price: 89,
    status: "active",
  },
];

export const demoLinks: SmartLink[] = [
  {
    id: "link-1",
    tenant_id: "tenant-auto",
    offer_id: "offer-cnh-b",
    code: "cnhb-7k2a",
    name: "CNH B - Instagram Stories",
    default_utm_source: "meta",
    default_utm_medium: "paid",
    default_utm_campaign: "cnh-b-julho",
    status: "active",
    offer_name: "CNH Categoria B",
    category: "Autoescola",
    clicks: 184,
    sales: 11,
    revenue: 25190,
    conversion_rate: 6,
  },
  {
    id: "link-2",
    tenant_id: "tenant-pet",
    offer_id: "offer-pet-banho",
    code: "banho-4d9q",
    name: "Banho e Tosa - Feed",
    default_utm_source: "meta",
    default_utm_medium: "paid",
    default_utm_campaign: "banho-tosa-bairro",
    status: "active",
    offer_name: "Banho e Tosa",
    category: "Pet shop",
    clicks: 96,
    sales: 19,
    revenue: 1691,
    conversion_rate: 19.8,
  },
];

export const demoLeads: Lead[] = [
  {
    id: "lead-1",
    tenant_id: "tenant-auto",
    ref: "a7k9-p2m4",
    lead_status: "new",
    clicked_at: new Date(Date.now() - 16 * 60000).toISOString(),
    utm_source: "meta",
    utm_medium: "paid",
    utm_campaign: "cnh-b-julho",
    link_name: "CNH B - Instagram Stories",
    link_code: "cnhb-7k2a",
    offer_name: "CNH Categoria B",
    category: "Autoescola",
    tags: [],
  },
  {
    id: "lead-2",
    tenant_id: "tenant-auto",
    ref: "b4td-8na2",
    lead_status: "sold",
    clicked_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    sold_at: new Date(Date.now() - 25 * 60000).toISOString(),
    revenue: 2290,
    customer_phone: "64999999999",
    utm_source: "meta",
    utm_campaign: "cnh-b-julho",
    link_name: "CNH B - Instagram Stories",
    offer_name: "CNH Categoria B",
    tags: ["venda"],
    lead_score: 100,
  },
  {
    id: "lead-4",
    tenant_id: "tenant-auto",
    ref: "q2mr-7s9a",
    lead_status: "qualified",
    clicked_at: new Date(Date.now() - 74 * 60000).toISOString(),
    qualified_at: new Date(Date.now() - 18 * 60000).toISOString(),
    utm_source: "meta",
    utm_medium: "paid",
    utm_campaign: "cnh-b-julho",
    link_name: "CNH B - Instagram Stories",
    link_code: "cnhb-7k2a",
    offer_name: "CNH Categoria B",
    category: "Autoescola",
    tags: ["bom lead", "remarketing"],
    lead_score: 80,
  },
  {
    id: "lead-5",
    tenant_id: "tenant-auto",
    ref: "r8vx-2k1n",
    lead_status: "bad",
    clicked_at: new Date(Date.now() - 115 * 60000).toISOString(),
    bad_at: new Date(Date.now() - 46 * 60000).toISOString(),
    utm_source: "meta",
    utm_medium: "paid",
    utm_campaign: "cnh-b-julho",
    link_name: "CNH B - Instagram Stories",
    link_code: "cnhb-7k2a",
    offer_name: "CNH Categoria B",
    category: "Autoescola",
    tags: ["ruim"],
    lead_score: -20,
  },
  {
    id: "lead-3",
    tenant_id: "tenant-pet",
    ref: "n8sa-4zq1",
    lead_status: "new",
    clicked_at: new Date(Date.now() - 42 * 60000).toISOString(),
    utm_source: "meta",
    utm_campaign: "banho-tosa-bairro",
    link_name: "Banho e Tosa - Feed",
    offer_name: "Banho e Tosa",
    tags: [],
  },
];

export const demoCapiEvents: CapiEvent[] = [
  { event_name: "QualifiedLead", ok: true, status_code: 200, created_at: new Date(Date.now() - 4 * 60000).toISOString() },
  { event_name: "Lead", ok: true, status_code: 200, created_at: new Date(Date.now() - 6 * 60000).toISOString() },
  { event_name: "Purchase", ok: true, status_code: 200, created_at: new Date(Date.now() - 24 * 60000).toISOString() },
  { event_name: "Lead", ok: true, status_code: 200, created_at: new Date(Date.now() - 60 * 60000).toISOString() },
];

export const demoHealth: CapiHealth = {
  total_events: 57,
  successful_events: 55,
  failed_events: 2,
  lead_events: 43,
  purchase_events: 12,
  success_rate: 96.5,
  last_event_at: demoCapiEvents[0].created_at,
};

export const demoCrmActivities: CrmActivity[] = [
  {
    id: "activity-1",
    tenant_id: "tenant-auto",
    tracking_session_id: "lead-4",
    activity_type: "stage_change",
    body: "Perfil tem urgencia para iniciar aulas.",
    from_status: "contacted",
    to_status: "qualified",
    created_at: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    id: "activity-2",
    tenant_id: "tenant-auto",
    tracking_session_id: "lead-5",
    activity_type: "stage_change",
    body: "Buscando outra cidade.",
    from_status: "contacted",
    to_status: "bad",
    created_at: new Date(Date.now() - 46 * 60000).toISOString(),
  },
  {
    id: "activity-3",
    tenant_id: "tenant-auto",
    tracking_session_id: "lead-2",
    activity_type: "stage_change",
    body: "Venda confirmada no atendimento.",
    from_status: "qualified",
    to_status: "sold",
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
];

export const demoMetaCampaigns: MetaCampaignRoi[] = [
  {
    tenant_id: "tenant-auto",
    campaign_id: "23861234567890001",
    campaign_name: "cnh-b-julho",
    spend: 812.45,
    impressions: 28450,
    reach: 16820,
    meta_clicks: 612,
    idx_leads: 184,
    idx_qualified: 41,
    idx_bad: 18,
    idx_sales: 11,
    idx_revenue: 25190,
    cpl: 4.42,
    cost_per_qualified: 19.82,
    quality_rate: 22.3,
    roas: 31.0,
  },
  {
    tenant_id: "tenant-pet",
    campaign_id: "23861234567890002",
    campaign_name: "banho-tosa-bairro",
    spend: 289.9,
    impressions: 10220,
    reach: 7110,
    meta_clicks: 238,
    idx_leads: 96,
    idx_qualified: 37,
    idx_bad: 9,
    idx_sales: 19,
    idx_revenue: 1691,
    cpl: 3.02,
    cost_per_qualified: 7.84,
    quality_rate: 38.5,
    roas: 5.83,
  },
];
